= Sample Quarkus Application:backend application
Simple RESTful API app with health check and configuration by properties file or environment variable.

== Application Overview
configuration can be set via environment variable or config/application.properties file

[options=header]
|===
|Variable|Description|Default Value
|version|Application Version|1.0.0-SNAPSHOT
|backend|target URL that backend request to|http://localhost:8080/version
|message|Message return from application|Hello, World
|===

URI supported by application
[options=header]
|===
|URI|Description
|/|Return Hello Message
|/health/live|Livenness probe URL
|/health/ready|Readiness probe URL
|/stop|Set liveness to false
|/start|Set liveness to true
|/not_ready|Set readiness to false
|/ready|Set readiness to true
|/version|Return App version

|===

== Build JAR
You need maven 3.5.4 at least.
[source,bash]
----
# package JAR
cd code
mvn clean package
# Run
java -jar target/backend-1.0.0-runner.jar
# Remark: Check that how fast it is!
# Test environment variables
export message=Bravo
export backend=https://httpbin.org/status/403
java -jar target/backend-1.0.0-runner.jar
----

== Build Native binary on OSX 

GraalVM 19.2.1 and XCode is needed.

[source,bash]
----
# Download GraalVM & Untar it
curl -o ~/Downloads/graalvm-ce-darwin-amd64-19.2.1.tar.gz \
https://github.com/oracle/graal/releases/download/vm-19.2.1/graalvm-ce-darwin-amd64-19.2.1.tar.gz
# Set GRAALVM_HOME variables
# e.g. GrallVM is installed at ${HOME}/opt
export GRAALVM_HOME=${HOME}/opt/graalvm-ce-19.2.1/Contents/Home
# Install Native Image
${GRAALVM_HOME}/bin/gu install native-image
# Package
mvn clean package -Pnative -DskipTests=true
# Run
target/backend-1.0.0-runner
# Test environment variable
export message=Bravo
export backend=http://httpbin.org/status/201
target/backend-1.0.0-runner
# Then cURL
curl -v http://localhost:8080
# Remark: To enable HTTPS, adding the -H:EnableURLProtocols=https
# -H:EnableURLProtocols=http,https --enable-all-security-services -H:+JNI
----


== Build Native Container Image 

Use multistage build as follow

[source,bash]
----
cd bin
docker build -f src/main/docker/Dockerfile.multistage \
-t ${CONTAINER_NAME} .
# Remark: Make use that .dockerignore included target,src and pom.xml
----

== Deploy to OpenShift (JVM Mode)
* Create binary build and patch to change strategy to docker strategy
[source,bash]
----
oc new-build --binary --name=backend -l app=backend
oc patch bc/backend -p "{\"spec\":{\"strategy\":{\"dockerStrategy\":{\"dockerfilePath\":\"src/main/docker/Dockerfile.jvm\"}}}}"
----

* Start build from current directory. Remark that this directory is base directory for src/main/docker/Dockerfile.jvm
[source,bash]
----
oc start-build backend --from-dir=. --follow
----

* Start deploy
[source,bash]
----
oc new-app --image-stream=backend:latest
----

* Pause deployment, set rediness and liveness probe
[source,bash]
----
oc rollout pause dc backend
oc set probe dc/backend --readiness --get-url=http://:8080/health/ready --initial-delay-seconds=15 --failure-threshold=1 --period-seconds=10
oc set probe dc/backend --liveness --get-url=http://:8080/health/live --initial-delay-seconds=10 --failure-threshold=3 --period-seconds=10
----

* Quarkus will overwrite configuration with config/application.properites
[source,bash]
----
oc create configmap backend --from-file=config/application.properties
oc set volume dc/backend --add --name=backend-config \
--mount-path=/deployments/config/application.properties \
--sub-path=application.properties \
--configmap-name=backend
----

* Expose service (create route) and resume rollout
[source,path]
----
oc expose svc backend
oc rollout resume dc backend
BACKEND_URL=$(oc get route backend -o jsonpath='{.spec.host}')
echo "Backend: http://$BACKEND_URL"
----

All in one shell script => link:build.sh[build.sh]

== Deploy to OpenShift (Native Mode)
WIP
[source,bash]
----
mvn package -Pnative -Dquarkus.native.container-build=true -DskipTests=true
----
