apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    build: backend-release-pipeline
  name: backend-release-pipeline
spec:
  nodeSelector: {}
  output: {}
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    contextDir: Jenkinsfile/release
    git:
      ref: master
      uri: https://gitlab.com/ocp-demo/backend_quarkus.git
    type: Git
  strategy:
    jenkinsPipelineStrategy:
      env:
      - name: STAGE_PROJECT
        value: stage
      - name: CICD_PROJECT
        value: ci-cd
      - name: NEXUS_REGISTRY_SVC
        value: docker://nexus-registry.ci-cd.svc.cluster.local:5000
      - name: BACKEND_URL
        value: https://httpbin.org/status/201
      - name: NEXUS_SECRET
        value: nexus-credential
      jenkinsfilePath: Jenkinsfile
    type: JenkinsPipeline
