= Sample Quarkus Application:backend application
Simple RESTful API app with health check and configuration by properties file or environment variable.

== Application Overview
configuration can be set via environment variable or config/application.properties file

[options=header]
|===
|Variable|Description|Default Value
|app.version|Application Version|1.0.0
|app.backend|target URL that backend request to|http://localhost:8080/version
|app.message|Message return from application|Hello, World
|app.showResponse|Show response from app.backend instead of app.message|false
|app.errorCodeNotLive|Return Code when liveness is false|504
|app.errorCodeNotReady|Return Code when readiness is false|503
|===

URI supported by application

[options=header]
|===
|URI|Description
|/|Return Hello Message
|/health/live|Livenness probe URL
|/health/ready|Readiness probe URL
|/stop|Set liveness to false
|/start|Set liveness to true
|/not_ready|Set readiness to false
|/ready|Set readiness to true
|/version|Return App version
|/openapi|Return OpenAPI (Swagger) document in yaml 
|/openapi?format=json|Return OpenAPI (Swagger) document in JSON 
|metrics/application|get metrics data
|===

== Build JAR
Quarkus 1.3.1 needs maven 3.6.3+ 

[source,bash]
----

# package JAR
cd code
mvn clean package

# Run
java -jar target/backend-1.0.0-runner.jar

# Remark: Check that how fast it is!
# Test environment variables
java -Dapp.showResponse=true -Dapp.backend=https://httpbin.org/delay/2 -jar target/backend-1.0.0-runner.jar

# Use environment variable
export APP_SHOWRESPONSE=true
export APP_BACKEND=https://httpbin.org/delay/2
java -jar  target/backend-1.0.0-runner.jar

----

Uber jar can be build with additional parameter

[source,bash]
----
# package UberJAR
cd code
mvn clean package -Dquarkus.package.uber-jar=true

----

== Build Native binary

Quarkus 1.3.1 needs GraalVM 19.3.1 or 20.0.0. XCode also needed for OSX. (link:../code/build_native.sh[build_native.sh])

[source,bash]
----
# Download GraalVM & Untar it
curl -o ~/Downloads/graalvm-ce-java8-darwin-amd64-20.0.0.tar.gz \
-L https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-20.0.0/graalvm-ce-java8-darwin-amd64-20.0.0.tar.gz

# Set GRAALVM_HOME variables
# e.g. GrallVM is installed at ${HOME}/opt
export GRAALVM_HOME=${HOME}/opt/graalvm-ce-java8-20.0.0/Contents/Home

# Install Native Image
${GRAALVM_HOME}/bin/gu install native-image

# Package
mvn clean package -Pnative -DskipTests=true

# Run
target/backend-1.0.0-runner

# Then cURL
curl -v http://localhost:8080
----

== Build JVM Container Image 

* Build container with Quarkus package as JAR (link:../code/build_jvm_container.sh[build_jvm_container.sh])

[source,bash]
----
cd code
mvn clean package

# Remark: Make sure that .dockerignore included target,src and pom.xml
docker build -f src/main/docker/Dockerfile.jvm \
-t ${CONTAINER_NAME}:${TAG} .

# Run
docker run -p 8080:8080 -e app.showResponse=true ${CONTAINERNAME}:${TAG}
----

* Because normally Quarkus will separate runnner and libraries. If you want single jar file (Uberjar). You an use parameter quarkus.pakage.uber-jar with value true to build uberjar. (link:../code/build_jvm_uberjar_container.sh[build_jvm_uberjar_container.sh])

[source,bash]
----
cd code
mvn clean package -Dquarkus.package.uber-jar=true

# Remark: Make sure that .dockerignore included target,src and pom.xml
docker build -f src/main/docker/Dockerfile.jvm_uberjar \
-t ${CONTAINER_NAME}:${TAG} .

# Run
docker run -p 8080:8080 -e app.showResponse=true ${CONTAINERNAME}:${TAG}
----

== Build Native Container Image 

* Use maven to build container native binary (link:../code/build_native_container.sh[build_native_container.sh])
[source,bash]
----
cd bin
# Specified paramter quarkus.native.container-build=true
mvn clean package -Dquarkus.native.container-build=true -DskipTests=true  -Pnative 

# Build
docker build -f src/main/docker/Dockerfile.native \
-t ${CONTAINER_NAME}:${TAG} .
----

* Use Mulitstage build (link:../code/build_native_container_multistage.sh[build_native_container_multistage.sh])

[source,bash]
----
cd bin
# Remark: Make sure that .dockerignore included target,src and pom.xml
docker build -f src/main/docker/Dockerfile.multistage \
-t ${CONTAINER_NAME}:${TAG} .

# Run
docker run -p 8080:8080 -e app.showResponse=true ${CONTAINERNAME}:${TAG}
----

== Deploy to OpenShift (JVM Mode)
* Create binary build and patch to change strategy to docker strategy

[source,bash]
----
oc new-build --binary --name=backend -l app=backend
oc patch bc/backend -p "{\"spec\":{\"strategy\":{\"dockerStrategy\":{\"dockerfilePath\":\"src/main/docker/Dockerfile.jvm\"}}}}"
----

* Start build from current directory. Remark that this directory is base directory for src/main/docker/Dockerfile.jvm

[source,bash]
----
oc start-build backend --from-dir=. --follow
----

* Start deploy

[source,bash]
----
oc new-app --image-stream=backend:latest
----

* Pause deployment, set rediness and liveness probe

[source,bash]
----
oc rollout pause dc backend
oc set probe dc/backend --readiness --get-url=http://:8080/health/ready --initial-delay-seconds=15 --failure-threshold=1 --period-seconds=10
oc set probe dc/backend --liveness --get-url=http://:8080/health/live --initial-delay-seconds=10 --failure-threshold=3 --period-seconds=10
----

* Quarkus will overwrite configuration with config/application.properites

[source,bash]
----
oc create configmap backend --from-file=config/application.properties
oc set volume dc/backend --add --name=backend-config \
--mount-path=/deployments/config/application.properties \
--sub-path=application.properties \
--configmap-name=backend
----

* Expose service (create route) and resume rollout

[source,bash]
----
oc expose svc backend
oc rollout resume dc backend
BACKEND_URL=$(oc get route backend -o jsonpath='{.spec.host}')
echo "Backend: http://$BACKEND_URL"
----

All in one shell script => link:../code/build.sh[build_ocp_jvm.sh]


== Deploy to OpenShift with S2I
S2I support both JVM and native container. You need to specified which S2I to use for build Quarkus container

Quarkus S2I need additional configuration in link:../code/.s2i/environment[.s2i/environment]

Example of .s2i/environment

[source,bash]
----
ARTIFACT_COPY_ARGS=-p -r lib/ *-runner.jar
JAVA_OPTIONS=-Dquarkus.http.host=0.0.0.0
----

Build JVM container by following command or use shell script link:../code/build_jvm_s2i.sh[build_jvm_s2i.sh]

[source,bash]
----

APP_NAME=backend
BASE_IMAGE=registry.access.redhat.com/redhat-openjdk-18/openjdk18-openshift
CONTEXT_DIR=code 
APP_REPOSITORY=https://gitlab.com/ocp-demo/backend_quarkus.git
oc new-app \
${BASE_IMAGE}~${APP_REPOSITORY} \
--context-dir=${CONTEXT_DIR} \
--name=${APP_NAME}

----

Build Native container by following command or use shell script link:../code/build_native_s2i.sh[build_native_s2i.sh]

[source,bash]
----

APP_NAME=backend-native
BASE_IMAGE=quay.io/quarkus/ubi-quarkus-native-s2i:19.3.1-java8
CONTEXT_DIR=code 
APP_REPOSITORY=https://gitlab.com/ocp-demo/backend_quarkus.git
oc new-app \
${BASE_IMAGE}~${APP_REPOSITORY} \
--context-dir=${CONTEXT_DIR} \
--name=${APP_NAME}

----
