commonLabels:
  environment: dev
commonAnnotations:
  description: This is dev environment
patchesStrategicMerge:
- backend.yaml
- backend-service.yaml
- backend-route.yaml
patchesJson6902:
- path: patch.yaml
  target:
    group: apps
    kind: Deployment
    name: backend
    version: v1
- path: patch.yaml
  target:
    kind: Service
    name: backend
    version: v1
- path: patch.yaml
  target:
    group: route.openshift.io
    kind: Route
    name: backend
    version: v1
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
images:
- name: quya.io/xyz
  newTag: latest
