commonLabels:
  environment: dev
commonAnnotations:
  description: This is dev environment
bases:
- ../../base
patchesStrategicMerge:
- backend.yaml
- backend-service.yaml
- backend-route.yaml
patchesJson6902:
- target:
    group: apps
    version: v1
    kind: Deployment
    name: backend
  path: patch.yaml
- target:
    version: v1
    kind: Service
    name: backend
  path: patch.yaml
- target:
    group: route.openshift.io
    version: v1
    kind: Route
    name: backend
  path: patch.yaml

