{
 "title": "Backend App",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Backend Request/sec",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "application_com_example_quarkus_BackendResource_timeBackend_rate_per_second"
    }
   ]
  },
  {
   "title": "Heap Size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "Bytes" }
   ],
   "targets": [
    { "expr": "base_memory_usedHeap_bytes" }
   ]
  },
  {
   "title": "Response Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "ms" }
   ],
   "targets": [
    {
     "expr": "application_com_example_quarkus_BackendResource_timeBackend_mean_seconds"
    }
   ]
  }
 ]
}